//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddGameApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int idGame { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Usesrs Usesrs { get; set; }
    }
}
