//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddGameApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.OrderList = new HashSet<OrderList>();
            this.Favorites = new HashSet<Favorites>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int idGPU { get; set; }
        public int idCPU { get; set; }
        public int idOC { get; set; }
        public int RAM { get; set; }
        public int diskSpace { get; set; }
        public int idGameMode { get; set; }
        public int idGameGenre { get; set; }
        public string description { get; set; }
        public int idDeveloper { get; set; }
        public string pathImage { get; set; }
        public decimal price { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public Nullable<double> discount { get; set; }
    
        public virtual CPU CPU { get; set; }
        public virtual Developers Developers { get; set; }
        public virtual GameGenre GameGenre { get; set; }
        public virtual GameMode GameMode { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual OC OC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderList> OrderList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
    }
}
