//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddGameApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int id { get; set; }
        public int idOrder { get; set; }
        public int idGame { get; set; }
        public decimal price { get; set; }
        public Nullable<double> discount { get; set; }
        public string keyGame { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
